# This file was generated by GoReleaser. DO NOT EDIT.
class Xnote < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/xiaofeizhao/xnote/releases/download/v0.1.0/xnote_0.1.0_Darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "2d063230ec0f0f638942433e1d28873d8bdf69547b0c4187084f12ccd31dbfeb"
  elsif OS.linux?
  end

  def install
    bin.install "xnote"
  end

  test do
    system "#{bin}/xnote --version"
  end
end
