# This file was generated by GoReleaser. DO NOT EDIT.
class Xnote < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/xiaofeizhao/xnote/releases/download/v0.1.0/xnote_0.1.0_Darwin_amd64.tar.gz"
    sha256 "6b7612ba70db72a69f2ed5d8ff114718b8cd5ac7542f59d6038e0f4db5fdbc86"
  elsif OS.linux?
  end

  def install
    bin.install "xnote"
  end

  test do
    system "#{bin}/xnote --version"
  end
end
