# This file was generated by GoReleaser. DO NOT EDIT.
class Xnote < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/xiaofeizhao/xnote/releases/download/v0.1.0/xnote_0.1.0_Darwin_amd64.tar.gz"
    sha256 "00b83a96c106462a9c09787ca576c4925ea2d31092a370de3d30d55637ddd8d8"
  elsif OS.linux?
  end

  def install
    bin.install "xnote"
  end

  test do
    system "#{bin}/xnote --version"
  end
end
